apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - image: longehdocker/task2-app
    name: flask-app
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: Password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  type: ClusterIP
  selector:
    app: flask-app
  ports:
  - port: 5000
    protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx
#  labels:
#    app: task2-nginx
#spec:
#  type: LoadBalancer
#  selector:
#    app: task2-nginx
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP