apiVersion: v1
kind: Pod
metadata:
  name: task2-app
  labels:
    app: flask
spec:
  containers:
  - image: longehdocker/task2-app
    name: task2-app
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: Password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  type: LoadBalancer
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx
#  labels:
#    app: task2-nginx
#spec:
#  type: LoadBalancer
#  selector:
#    app: task2-nginx
#  ports:
#    - port: 80
#      targetPort: 80
#      protocol: TCP