apiVersion: v1
kind: Pod
metadata:
  name: task2
  labels:
    app: task2-app
spec:
  containers:
  - image: longehdocker/task2jenk
    name: task2
    env:
      - name: MY_SQL_PASSWORD
        value: Password
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: task2-app
spec:
  type: LoadBalancer
  selector:
    app: task2-app
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: task2-nginx
spec:
  type: LoadBalancer
  selector:
    app: task2-nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP