apiVersion: v1
kind: Pod
metadata:
  name: task2-db
  labels:
    app: task2-db
spec:
  containers:
  - image: longehdocker/task2jenk
    name: task2
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: Password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: task2-db
spec:
  type: ClusterIP
  selector:
    app: task2-db
  ports:
    - port: 3306
      targetPort: 3306